### ISSUE TITLE
error when i stroke s.th with the following message!

### ISSUE THREAD

**Issue by cheoljoo** [wonmin82/dotfiles#7]
Error detected while processing function UltiSnips#TrackChange:
line    1:
E319: Sorry, the command is not available in this version:     py3 UltiSnips_Manager._track_change()
Press ENTER or type command to continue

[ubuntu 14.04]

**Comment by wonmin82** [comment]
Remove following line in .vimrc
 
`NeoBundle 'SirVer/ultisnips`

I have gave up the compatibility for Ubuntu 14.04. I don't use that version any more, and it is impossible because lots of dependencies don't provide compatibility for that version.

**Comment by cheoljoo** [comment]
thanks a lot.
